language: cpp
compiler: clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-multilib

install:
  - wget http://www.sourcemod.net/smdrop/1.6/sourcemod-1.6.0-git4525-linux.tar.gz -O /tmp/sourcemod.tar.gz
  - tar -xzvf /tmp/sourcemod.tar.gz

before_script:
  - chmod +rx addons/sourcemod/scripting/spcomp
  - chmod +rx addons/sourcemod/scripting/compile.sh
  - cd addons/sourcemod/scripting/
  
script:
  - ./spcomp nativevotes.sp
  - ./spcomp nativevotes-basecommands.sp
  - ./spcomp nativevotes_votetest.sp
  - ./spcomp nativevotes_votemanager_test.sp
  - ./spcomp nativevotes_mapchooser.sp
  